site_name: Hello-Logic
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/test.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - 'css/custom.css'
# Page tree
nav:
  # - 第 1 章 &nbsp; 什么是逻辑:
  # - 第 2 章 &nbsp; 谓词逻辑:
  # - 第 3 章 &nbsp; 模态逻辑:
  - 第 13 章 &nbsp; 描述逻辑:
    - 0. 总览: description_logic/overview/index.html
    - 1. 背景: description_logic/background/index.html
    - 2. 定义: description_logic/definition/index.html
    - 3. 推理: description_logic/reasoning/index.html
    - 4. 计算复杂性: description_logic/complexity/index.html
    - 5. 非标准系统: description_logic/non_standard/index.html
    - 6. 当代进展: description_logic/present/index.html
    - 7. 哲学洞察: description_logic/philosophy/index.html
    - 附录 : description_logic/snapshot/index.html
  - 第 14 章 &nbsp; 非单调逻辑:
    - 0. 总览: Non-monotonic Logic/NML/index.html